name: Deploy APIs
on:
  push:
    branches: [ "main" ]
    paths: ["api/**/*.py"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Copy API files
        run: cp -r api/*.py .
      - name: Commit changes
        run: |
          git config user.name "${{ secrets.GITHUB_USER }}"
          git config user.email "${{ secrets.GITHUB_EMAIL }}"
          git add -A
          git commit -m "Deploy API files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
