name: Deploy APIs
on:
  push:
    branches: [ "main" ]
    paths: ["api/*.py"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy api/*.py files from main to gh-pages
        run: |
          cp -R main/api/ gh-pages/

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: YorkJong
          author_email: york.jong@gmail.com
          message: "Update api/*.py files"
          add: .
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
