# Deploy Vercel Serverless Functions
name: Deploy Functions
on:
  push:
    branches: [ "main" ]
    paths: ["api/*.py", "requirements.txt", "vercel.json"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy main/api/*.py
        run: |
          [ -d gh-pages/api ] || mkdir gh-pages/api
          cp main/api/*.py gh-pages/api/

      - name: Copy requirements.txt and vercel.json
        run: |
          for file in requirements.txt vercel.json
          do
            cp main/"$file" gh-pages/
          done

      - name: Copy latest journal (YYYY_MM_DD.md)
        run: |
          latest=$(find main/journals -name "????_??_??.md" | sort -r | head -n 1)
          cp "$latest" gh-pages/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config --local user.email "york.jong@gmail.com"
          git config --local user.name "York Jong"
          git add .
          git commit -m "Update api/*.py files and requirements.txt"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
