# Deploy Vercel Serverless Functions
name: Deploy Functions
on:
  push:
    branches: [ "main" ]
    paths: ["api/*.py", "requirements.txt", "vercel.json"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set environment variables to GITHUB_ENV
        run: |
          echo "SRC_FOLDER=main" >> $GITHUB_ENV
          echo "TGT_FOLDER=gh-pages" >> $GITHUB_ENV
      - name: Copy src/*.py
        run: |
          mkdir -p "${{ env.TGT_FOLDER }}/src"
          cp "${{ env.SRC_FOLDER }}/src/"*.py "${{ env.TGT_FOLDER }}/src/"
      - name: Copy api/*.py
        run: |
          mkdir -p "${{ env.TGT_FOLDER }}/api"
          cp "${{ env.SRC_FOLDER }}/api/"*.py "${{ env.TGT_FOLDER }}/api/"
      - name: Copy requirements.txt and vercel.json
        run: |
          for file in requirements.txt vercel.json
          do
            cp "${{ env.SRC_FOLDER }}/$file" "${{ env.TGT_FOLDER }}/"
          done
      - name: Copy latest journal (YYYY_MM_DD.md)
        run: |
          latest=$(find "${{ env.SRC_FOLDER }}/journals" -name "????_??_??.md" | sort -r | head -n 1)
          cp "$latest" "${{ env.TGT_FOLDER }}/"

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config --local user.email "york.jong@gmail.com"
          git config --local user.name "York Jong"
          git add .
          git commit -m "Update api/*.py files, requirements.txt, and vercel.json"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
