# This is a basic workflow to help you get started with Actions

name: Publish Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch with given paths
  push:
    branches: [ "main" ]
    paths: ["journals/**", "pages/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@v0.1
      - name: add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: remove trace.zip
        run: rm $GITHUB_WORKSPACE/www/trace.zip
      - name: Install feedgen
        run: pip install feedgen
      - name: Generate IT.rss
        run: python api/feed.py "IT" > $GITHUB_WORKSPACE/www/IT.rss
      - name: Generate Crypto.rss
        run: python api/feed.py "Crypto" > $GITHUB_WORKSPACE/www/Crypto.rss
      - name: Generate Taiwan.rss
        run: python api/feed.py "Crypto" > $GITHUB_WORKSPACE/www/Taiwan.rss
      - name: Generate news.rss (Tesla, Tech, Finance)
        run: python api/feed.py "Tesla, Tech, Finance" > $GITHUB_WORKSPACE/www/news.rss
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
