# This is a basic workflow to help you get started with Actions

name: Publish Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch with given paths
  push:
    branches: [ "main" ]
    paths: ["journals/**", "pages/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@v0.1
      - name: add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: remove trace.zip
        run: rm www/trace.zip

      - name: Copy api/*.py
        run: |
          [ -d www/api ] || mkdir www/api
          cp api/*.py www/api/
      - name: Copy requirements.txt
        run: cp requirements.txt www/
      - name: Copy vercel.json
        run: cp vercel.json www/

      - name: Copy latest journal (YYYY_MM_DD.md)
        run: |
          latest=$(find journals -name "????_??_??.md" | sort -r | head -n 1)
          cp $latest www/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
